### ISSUE TITLE
Possibility to add resize from anchor

### ISSUE THREAD

**Issue by notchris** [tocttou/three-freeform-controls#8]
Hello! This library looks awesome. I'm wondering how to implement something like resize controls where you can resize from the bounds of an object in one direction? Similar to these controls: https://konvajs.org/docs/select_and_transform/Basic_demo.html

Not sure if this is possible, but thought I'd ask!

Thank you

**Comment by tocttou** [comment]
Hi Chris

This could be a nice addition. Let me see if I can make a quick demo.

**Comment by notchris** [comment]
That would be awesome! The problems I faced when trying to do something similar was computing scale with mouse movement. I think I was trying to use delta over mouse position vs last.

**Comment by notchris** [comment]
Here is a nice example of a similar style editor in Blender: https://youtu.be/ieCB8FzjlqY

**Comment by notchris** [comment]
@tocttou How do you calculate the correct scale amount based on mouse position? I know you can't do it with the mouse delta. Is there an equation?

**Comment by tocttou** [comment]
Closing because of no bandwidth available at this point :(
